# Generated by Django 5.1.2 on 2025-01-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bid_active',
            field=models.BooleanField(default=False, verbose_name='is bit active?'),
        ),
    ]
