# Generated by Django 5.1.2 on 2025-02-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_product_bid_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bid_active',
        ),
        migrations.AddField(
            model_name='product',
            name='bid_status',
            field=models.BooleanField(default=False, verbose_name='bit status'),
        ),
    ]
