# Generated by Django 5.1.2 on 2025-02-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_remove_product_bid_active_product_bid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('software', 'Software'), ('hardware', 'Hardware'), ('EEMS', 'Electronics (embedded systems)')], default='software', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
