# Generated by Django 5.1.2 on 2025-02-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_remove_product_bid_active_product_bid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[(1, 'Software'), (2, 'Hardware'), (3, 'Electronics (embedded systems)')], default=1, max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
