# Generated by Django 5.1.2 on 2025-02-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_product_category_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[(0, '--SELECT CATEGORY--'), (1, 'Software'), (2, 'Hardware'), (3, 'Electronics (embedded systems)')], default=0, max_length=5),
        ),
    ]
