# Generated by Django 5.1.2 on 2025-02-24 15:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_remove_history_product_name_and_more'),
        ('seller', '0005_alter_bid_bidder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='date_of_sale',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='sale_price',
        ),
        migrations.AddField(
            model_name='product',
            name='highest_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='highest_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bids_won', to='buyer.buyer'),
        ),
        migrations.AddField(
            model_name='sales',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='buyer.buyer'),
        ),
        migrations.AddField(
            model_name='sales',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='sale_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sale Date'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bid Amount'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Bid Time'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='buyer.buyer'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='seller.product'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='seller.product'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='seller.seller'),
        ),
    ]
