# Generated by Django 5.1.2 on 2025-06-11 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0009_rename_paymentstatus_payments'),
        ('seller', '0006_remove_sales_date_of_sale_remove_sales_sale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='buyer.payments'),
        ),
    ]
