# Generated by Django 5.1.2 on 2025-06-11 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0010_rename_payments_payment'),
        ('seller', '0007_sales_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sales',
            new_name='Sale',
        ),
    ]
