# Generated by Django 5.1.2 on 2025-06-11 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0010_rename_payments_payment'),
        ('seller', '0008_rename_sales_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='buyer.payment'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='seller.product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='seller.seller'),
        ),
    ]
