# Generated by Django 5.1.2 on 2025-06-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_alter_sale_payment_alter_sale_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routeerror',
            old_name='field',
            new_name='route',
        ),
        migrations.AddField(
            model_name='routeerror',
            name='eid',
            field=models.CharField(default='xxxxx-xxxxx', max_length=15),
        ),
    ]
