# Generated by Django 5.2.3 on 2025-07-02 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0013_buyer_is_verified'),
        ('seller', '0010_rename_field_routeerror_route_routeerror_eid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='buyer.buyer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale', to='buyer.payment'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale', to='seller.product'),
        ),
    ]
