# Generated by Django 5.2.3 on 2025-07-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_alter_sale_buyer_alter_sale_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='id',
            field=models.IntegerField(default=1010101010, max_length=10, primary_key=True, serialize=False),
        ),
    ]
