# Generated by Django 5.2.3 on 2025-07-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0012_alter_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='id',
            field=models.CharField(default='xxxxxxxxxx', max_length=10, primary_key=True, serialize=False),
        ),
    ]
