# Generated by Django 5.2.3 on 2025-07-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0013_alter_seller_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='id',
            new_name='uid',
        ),
        migrations.AddField(
            model_name='seller',
            name='twoFA_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
