# Generated by Django 5.2.3 on 2025-07-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0014_rename_id_seller_uid_seller_twofa_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='qr_code_path',
            field=models.ImageField(blank=True, null=True, upload_to='auth-QRs/'),
        ),
    ]
