# Generated by Django 5.2.3 on 2025-07-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0015_seller_qr_code_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='fullname',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
