# Generated by Django 5.2.3 on 2025-07-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0016_alter_seller_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
