# Generated by Django 5.2.3 on 2025-07-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0017_alter_seller_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routeerror',
            name='id',
        ),
        migrations.AlterField(
            model_name='routeerror',
            name='eid',
            field=models.CharField(default='xxxxx-xxxxx', max_length=15, primary_key=True, serialize=False),
        ),
    ]
