# Generated by Django 5.2.3 on 2025-07-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0018_remove_routeerror_id_alter_routeerror_eid'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
