# Generated by Django 5.2.3 on 2025-07-06 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0019_seller_code_expires_at_seller_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codes', models.JSONField(blank=True, default=list)),
                ('used_codes', models.JSONField(blank=True, default=list)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to='seller.seller')),
            ],
        ),
    ]
