# Generated by Django 5.2.3 on 2025-07-06 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0020_backupcodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupcodes',
            name='used_codes',
        ),
    ]
