# Generated by Django 5.1.2 on 2025-01-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='fullname',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='buyer',
            name='password',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
