# Generated by Django 5.1.2 on 2025-02-19 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_rename_fullname_buyer_username_alter_buyer_password_and_more'),
        ('seller', '0005_alter_bid_bidder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='history',
            name='seller_phone_no',
        ),
        migrations.AddField(
            model_name='history',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seller.product'),
        ),
        migrations.AddField(
            model_name='history',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seller.seller'),
        ),
    ]
