# Generated by Django 5.1.2 on 2025-05-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_remove_history_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='phone',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
