# Generated by Django 5.1.2 on 2025-06-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_alter_buyer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
