# Generated by Django 5.1.2 on 2025-06-10 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_paymentstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentstatus',
            name='email',
        ),
    ]
