# Generated by Django 5.1.2 on 2025-06-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0007_remove_paymentstatus_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='fullname',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
