# Generated by Django 5.1.2 on 2025-06-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0008_buyer_fullname'),
        ('seller', '0006_remove_sales_date_of_sale_remove_sales_sale_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentStatus',
            new_name='Payments',
        ),
    ]
