# Generated by Django 5.1.2 on 2025-06-11 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0009_rename_paymentstatus_payments'),
        ('seller', '0007_sales_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
    ]
