# Generated by Django 5.1.2 on 2025-06-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0010_rename_payments_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='Online Payment', max_length=50),
        ),
        migrations.AddField(
            model_name='routeerror',
            name='eid',
            field=models.CharField(default='xxxxx-xxxxx', max_length=15),
        ),
    ]
