# Generated by Django 5.1.2 on 2025-06-21 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0011_payment_payment_method_routeerror_eid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routeerror',
            old_name='field',
            new_name='route',
        ),
    ]
