# Generated by Django 5.2.3 on 2025-06-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0012_rename_field_routeerror_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
