# Generated by Django 5.2.3 on 2025-07-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0013_buyer_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='fullname',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
