# Generated by Django 5.2.3 on 2025-07-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0016_alter_buyer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='id',
            new_name='uid',
        ),
    ]
